-- MySQL Script generated by MySQL Workbench
-- Sat Apr  8 18:54:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_objetivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` INT NOT NULL,
  `nivel_minimo` INT NOT NULL,
  `xp` INT NOT NULL,
  `preco` INT NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_curso_idx` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_curso`
    FOREIGN KEY (`tipo`)
    REFERENCES `mydb`.`tipo_objetivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habilidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `incremento_dinheiro` DECIMAL NOT NULL,
  `nivel_minimo` INT NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  `curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_curso_habilidade_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_curso_habilidade`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `incremento_dinheiro` DECIMAL NOT NULL,
  `preco` INT NOT NULL,
  `metro` INT NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  `nivel_minimo` INT NOT NULL,
  `curso` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_curso_receita_idx` (`curso` ASC) VISIBLE,
  CONSTRAINT `fk_curso_receita`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habilidade_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habilidade_receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `habilidade_id` INT NOT NULL,
  `receita_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receita_habilidade_receita_idx` (`receita_id` ASC) VISIBLE,
  INDEX `fk_habilidades_habilidades_receitas_idx` (`habilidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_receitas_habilidades_receitas`
    FOREIGN KEY (`receita_id`)
    REFERENCES `mydb`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habilidades_habilidades_receitas`
    FOREIGN KEY (`habilidade_id`)
    REFERENCES `mydb`.`habilidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ferramenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ferramenta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `incremento_dinheiro` DECIMAL NOT NULL,
  `preco` INT NOT NULL,
  `nivel_minimo` INT NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ferramenta_receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ferramenta_receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ferramenta_id` INT NOT NULL,
  `receita_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_receitas_ferramentas_receitas_idx` (`receita_id` ASC) VISIBLE,
  INDEX `fk_ferramentas_ferramentas_receitas_idx` (`ferramenta_id` ASC) VISIBLE,
  CONSTRAINT `fk_receitas_ferramentas_receitas`
    FOREIGN KEY (`receita_id`)
    REFERENCES `mydb`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ferramentas_ferramentas_receitas`
    FOREIGN KEY (`ferramenta_id`)
    REFERENCES `mydb`.`ferramenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`novelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`novelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `malha` VARCHAR(45) NOT NULL,
  `tamanho_padrao` INT NOT NULL,
  `preco` INT NOT NULL,
  `incremento_dinheiro` DECIMAL NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_premio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_premio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`missao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `tipo_objetivo` INT NOT NULL,
  `objetivo` INT NOT NULL,
  `nivel_minimo` INT NOT NULL,
  `premio` INT NOT NULL,
  `tipo_premio` INT NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_tipo_missao_idx` (`tipo_objetivo` ASC) VISIBLE,
  INDEX `fk_missao_tipo_premio_idx` (`tipo_premio` ASC) VISIBLE,
  CONSTRAINT `fk_missao_tipo_objetivo`
    FOREIGN KEY (`tipo_objetivo`)
    REFERENCES `mydb`.`tipo_objetivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_missao_tipo_premio`
    FOREIGN KEY (`tipo_premio`)
    REFERENCES `mydb`.`tipo_premio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `xp` INT NOT NULL,
  `nivel` INT NOT NULL,
  `dinheiro` INT NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_missao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_missao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `missao` INT NOT NULL,
  `progresso` INT ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_usuario_missao_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_missao_usuario_missao_idx` (`missao` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_usuario_missao`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_missao_usuario_missao`
    FOREIGN KEY (`missao`)
    REFERENCES `mydb`.`missao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` INT NOT NULL,
  `vendido` VARCHAR(1) NOT NULL,
  `receita` INT NOT NULL,
  `usuario` INT NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_receita_trico_idx` (`receita` ASC) VISIBLE,
  INDEX `fk_usuario_trico_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_receita_trico`
    FOREIGN KEY (`receita`)
    REFERENCES `mydb`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_trico`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`novelo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`novelo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `novelo` INT NOT NULL,
  `tamanho` INT NOT NULL,
  `ativo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_novelo_trico_novelo_idx` (`novelo` ASC) VISIBLE,
  INDEX `fk_usuario_usuario_novelo_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_novelo_usuario_novelo`
    FOREIGN KEY (`novelo`)
    REFERENCES `mydb`.`novelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario_novelo`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trico_novelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trico_novelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trico` INT NOT NULL,
  `novelo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trico_trico_novelo_idx` (`trico` ASC) VISIBLE,
  INDEX `fk_novelo_trico_novelo_idx` (`novelo` ASC) VISIBLE,
  CONSTRAINT `fk_trico_trico_novelo`
    FOREIGN KEY (`trico`)
    REFERENCES `mydb`.`trico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_novelo_trico_novelo`
    FOREIGN KEY (`novelo`)
    REFERENCES `mydb`.`novelo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`curso_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `curso` INT NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_curso_curso_usuario_idx` (`curso` ASC) VISIBLE,
  INDEX `fk_usuario_curso_usuario_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_curso_curso_usuario`
    FOREIGN KEY (`curso`)
    REFERENCES `mydb`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_curso_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ferramenta_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ferramenta_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ferramenta` INT NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ferramenta_ferramenta_usuario_idx` (`ferramenta` ASC) VISIBLE,
  INDEX `fk_usuario_ferramenta_usuario_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_ferramenta_ferramenta_usuario`
    FOREIGN KEY (`ferramenta`)
    REFERENCES `mydb`.`ferramenta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_ferramenta_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habilidade_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habilidade_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `habilidade` INT NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_habilidade_habilidade_usuario_idx` (`habilidade` ASC) VISIBLE,
  INDEX `fk_usuario_habilidade_usuario_idx` (`usuario` ASC) VISIBLE,
  CONSTRAINT `fk_habilidade_habilidade_usuario`
    FOREIGN KEY (`habilidade`)
    REFERENCES `mydb`.`habilidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_habilidade_usuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario-receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario-receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `receita` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk-usuario-usuario-receita_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk-receita-usuario-receita_idx` (`receita` ASC) VISIBLE,
  CONSTRAINT `fk-usuario-usuario-receita`
    FOREIGN KEY (`usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk-receita-usuario-receita`
    FOREIGN KEY (`receita`)
    REFERENCES `mydb`.`receita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
